version: 2.1

orbs:
  node: circleci/node@5.0.0

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - npm-readonly
      - publish:
          context:
            - npm-publish
            - github
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: circleci/node:erbium
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - node/install-packages
      - run: npm run build
      - run: npm test

  publish:
    docker:
      - image: circleci/node:erbium
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - node/install-packages
      - run: npm run semantic-release
